version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_DB=college_db
      - POSTGRES_PASSWORD=db_password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432
  api:
    build:
      context: .
      dockerfile: ./dockerfile.api
    volumes:
      - .:/app:delegated
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - check-db-started
  check-db-started:
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:5432'

volumes:
  db:
