version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_DB=products
      - POSTGRES_PASSWORD=db_password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_EXT}:${DB_PORT}
  api:
    build:
      context: .
      dockerfile: ./dockerfile.api
    volumes:
      - .:/app:delegated
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db

volumes:
  db:
